-- database/oracle/schema.sql
-- Create schema for analytical tables and daily aggregates

CREATE TABLE flights_warehouse (
    flight_id VARCHAR2(50),
    callsign VARCHAR2(50),
    origin VARCHAR2(100),
    destination VARCHAR2(100),
    first_seen TIMESTAMP,
    last_seen TIMESTAMP,
    PRIMARY KEY (flight_id)
);

CREATE TABLE positions_warehouse (
    position_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    flight_id VARCHAR2(50),
    observed_at TIMESTAMP,
    lat NUMBER(12,8),
    lon NUMBER(12,8),
    altitude NUMBER,
    speed NUMBER,
    heading NUMBER
);

-- Aggregation table: daily per-flight stats
CREATE TABLE daily_flight_stats (
    flight_id VARCHAR2(50),
    stat_date DATE,
    total_positions NUMBER,
    avg_speed NUMBER,
    max_altitude NUMBER,
    min_altitude NUMBER,
    PRIMARY KEY (flight_id, stat_date)
);

-- Optional PL/SQL job snippet to populate daily_flight_stats (example)
-- You can schedule this job using DBMS_SCHEDULER
